apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-data-argo
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-experiments-argo
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
