apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-cwsscheduleraccount
  namespace: argo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-cwsschedulerrole
  namespace: argo
rules:
 - apiGroups: [""]
   resources: ["pods","pods/status","pods/exec","nodes","bindings","configmaps"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
 - apiGroups: ["metrics.k8s.io"]
   resources: ["nodes"]
   verbs: ["get","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: argo-cwsschedulerbinding
   namespace: argo
subjects:
 - kind: ServiceAccount
   name: argo-cwsscheduleraccount
   namespace: argo
roleRef:
   kind: ClusterRole
   name: argo-cwsschedulerrole
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: argo
    component: scheduler
    tier: control-plane
  name: workflow-scheduler
spec:
  nodeSelector:
    usedby: ftschirpke
  containers:
  - env:
    - name: spring_profiles_active
      value: dev
    - name: SCHEDULER_NAME
      value: workflow-scheduler
    - name: AUTOCLOSE
      value: "false"
    # image: commonworkflowscheduler/kubernetesscheduler:2.1
    image: friedricht/cws_local
    imagePullPolicy: Always
    name: workflow-scheduler
    resources:
      requests:
        cpu: "1"
        memory: 2000Mi
    volumeMounts:
    - mountPath: /input
      name: data
  securityContext:
    runAsUser: 0
  serviceAccount: argo-cwsscheduleraccount
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ceph-data-argo
